name: SwordofMagic10
version: 'Dev'
main: SwordofMagic10.SomCore
api-version: 1.19
folia-supported: true
depend:
  - LibsDisguises
  - ProtocolLib

commands:
  Test:
    permission: som10.dev
    description: description
    usage: /<command>
  SomReload:
    permission: som10.reload
    description: description
    usage: /<command>
  SomRestart:
    permission: som10.dev
    description: description
    usage: /<command>
  Save:
    permission: som10.dev
    description: description
    usage: /<command>
  Load:
    permission: som10.dev
    description: description
    usage: /<command>
  CloneLoad:
    permission: som10.dev
    description: description
    usage: /<command>
  MobClear:
    permission: som10.dev
    description: description
    usage: /<command>
  MobSpawn:
    permission: som10.dev
    description: description
    usage: /<command>
  PlayMode:
    aliases: pm
    permission: som10.dev
    description: description
    usage: /<command>
  GetItem:
    permission: som10.dev
    description: description
    usage: /<command>
  SetLevel:
    permission: som10.dev
    description: description
    usage: /<command>
  BossBarMessage:
    permission: som10.dev
    description: description
    usage: /<command>
  DisplayParticle:
    aliases: dp
    permission: som10.dev
    description: description
    usage: /<command>
  Heal:
    permission: som10.dev
    description: description
    usage: /<command>
  ClearCT:
    permission: som10.dev
    description: description
    usage: /<command>
  FlySpeed:
    permission: som10.dev
    description: description
    usage: /<command>
  RaidEnter:
    permission: som10.dev
    description: description
    usage: /<command>
  GetEffect:
    permission: som10.dev
    description: description
    usage: /<command>
  AFK:
    permission: som10.dev
    description: description
    usage: /<command>
  Cast:
    permission: som10.dev
    description: description
    usage: /<command>
  TPMap:
    permission: som10.dev
    description: description
    usage: /<command>
  PlayerVote:
    permission: som10.dev
    description: description
    usage: /<command>

  Menu:
    aliases: m
    description: description
    usage: /<command>
  Party:
    aliases: pt
    description: description
    usage: /<command>
  SkipDeath:
    aliases: sd
    description: description
    usage: /<command>
  PlayerRide:
    aliases: pr
    description: description
    usage: /<command>
  ParticleDensity:
    aliases: pd
    description: description
    usage: /<command>
  ParticleDensityOther:
    aliases: pdo
    description: description
    usage: /<command>
  ParticleDensityEnemy:
    aliases: pde
    description: description
    usage: /<command>
  Death:
    description: description
    usage: /<command>
  TalkSpeed:
    aliases: ts
    description: description
    usage: /<command>
  Help:
    aliases: h
    description: description
    usage: /<command>
  DamageLog:
    description: description
    usage: /<command>
  ExpLog:
    description: description
    usage: /<command>
  ItemLog:
    description: description
    usage: /<command>
  BuffLog:
    description: description
    usage: /<command>
  SkillLog:
    description: description
    usage: /<command>
  QuickCast:
    description: description
    usage: /<command>
  PvP:
    description: description
    usage: /<command>
  Trade:
    description: description
    usage: /<command>
  PlayerInfo:
    aliases: pi
    description: description
    usage: /<command>
  Auction:
    description: description
    usage: /<command>
  EffectInfo:
    aliases: ei
    description: description
    usage: /<command>
  GatheringDrop:
    aliases: gd
    description: description
    usage: /<command>
  ViewItem:
    aliases: vi
    description: description
    usage: /<command>
  Market:
    description: description
    usage: /<command>
  Order:
    description: description
    usage: /<command>
  ViewAmount:
    aliases: va
    description: description
    usage: /<command>
  ReqClassExp:
    description: description
    usage: /<command>
  ReqGatheringExp:
    description: description
    usage: /<command>
  SearchSpawner:
    description: description
    usage: /<command>
  PetName:
    description: description
    usage: /<command>
  Favorite:
    description: description
    usage: /<command>
  PushStorage:
    description: description
    usage: /<command>